version: "2"

services:
    postgres:
        image: postgres:15
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - POSTGRES_DB=postgres
        restart: unless-stopped
        volumes:
            - /var/lib/postgresql/data:/var/lib/postgresql/data

    erp:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - postgres
        ports:
            - "8069:8069"
            - "8072:8072"
        tty: true
        environment:
            - DB_HOST=postgres
            - DB_USER=odoo
            - DB_PASSWORD=odoo
            - DB_PORT=5432
        volumes:
            - /var/lib/erp_data:/var/lib/odoo
        restart: unless-stopped
